name: Setup
description: Setup Build Step

runs:
  using: "composite"
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        cache: 'yarn'

    - name: Install dependencies
      shell: bash
      run: yarn install --frozen-lockfile

    - name: Turbo Cache
      uses: actions/cache@v4
      with:
        path: .turbo
        key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
        restore-keys: |
          turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
          turbo-${{ github.job }}-${{ github.ref_name }}-
          turbo-${{ github.job }}-
