import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

if (process.env.NODE_ENV !== 'production') {
  import('@envyjs/nextjs').then(({ enableTracing }) => {
    enableTracing({ serviceName: 'example-nextjs', ignoreRSC: true, debug: true });
  });
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
