name: Release
on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/build-test

  publish:
    runs-on: ubuntu-latest
    needs: [lint, test]
    permissions:
      contents: write
      id-token: write
      issues: write
      repository-projects: write
      deployments: write
      packages: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup

      - name: Build
        run: yarn build --cache-dir=".turbo"
        env:
          NODE_ENV: production

      - uses: changesets/action@v1
        with:
          version: yarn run changeset version
          publish: yarn run changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
